services:
  home-server-bot:
    build: .
    container_name: home_server_bot
    restart: always
    network_mode: "host"
    cap_add:
      - NET_ADMIN
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./data:/app/data
      - ~/.ssh/id_rsa:/app/ssh/id_rsa:ro
